export class Manifiesto{
	constructor(
		public id: number,
		public modelo: string,
		public lote: string,
		public qty:string, 
		public panel: string,
		public op: string,
		public semielaborado: string,
		public version: string,
		public linea: string,
		public carril: string,
		public proceso: string, 
		public pcb: string, 
		public lado: string,
		public stencil: any,
		public ubicacion_stencil: any, 
		public printer: string,
		public prog_printer: string,
		public spi:string, 
		public prog_spi:string, 
		public gota1:string,
		public prog_gota_1: string,
		public gota2:string,
		public prog_gota_2: string,
		public pyp1:string,
		public prog_pyp_1: string,
		public pyp2:string,
		public prog_pyp_2: string,
		public consumible: string, 
		public horno: string, 
		public perfil_horno: string,
		public grabado: string, 
		public aoi_intermedia:string,
		public prog_aoi_intermedia: string,
		public invalidacion_aoi_intermedia: string, 
		public aoi:string, 
		public prog_aoi: string,
		public invalidacion_aoi: string,
		public created_at: any,
		public updated_at: any,
		public version_manifiesto:any,
		public manual:number,
		public comentario:string 

		){}
}